name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare build-agent
        run: |
          df -h
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Git: checkout releases
        run: git checkout releases

      - name: Git: merge master
        run: git merge master

      - name: Helm: lint
        run: make lint
